services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app1
      - app2
  
  app1:
    image: httpd:alpine
    container_name: app1
    restart: always
  
  app2:
    image: nginx:alpine
    container_name: app2
    restart: always