services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-net
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "${APP_PORT}:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/tododb
    depends_on:
      - mongo
    networks:
      - todo-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/todos"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:

networks:
  todo-net: