version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
