services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
    - 2368:2368
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: mysql   # <- NOT localhost or 127.0.0.1
      database__connection__user: ghost
      database__connection__password: ghostpass
      database__connection__database: ghostdb
    volumes:
      - ./content:/var/lib/ghost/content
  
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - ghost_mysql_data:/var/lib/mysql

volumes:
  ghost_mysql_data: