services:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    networks:
      - jenkins
    environment:
      DOCKER_TLS_CERTDIR: ""
  
  jenkins:
    image: ${JENKINS_IMAGE}
    container_name: jenkins
    user: root
    ports:
      - "${JENKINS_PORT_HTTP}:8080"
      - "${JENKINS_AGENT_PORT}:50000"
    volumes:
      - ${JENKINS_VOLUME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - dind
    networks:
      - jenkins

  nginx:
    image: ${NGINX_IMAGE}
    container_name: jenkins-nginx
    ports:
      - "${JENKINS_PORT_HTTPS}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - jenkins
    networks:
      - jenkins


volumes:
  jenkins_home:

networks:
  jenkins: