pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo Building Docker container...'
                sh 'docker --version'
            }
        }
        stage('Test') {
            steps {
                sh 'echo Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo Deploying application...'
            }
        }
    }
}
